[build]
    command = "vite build"
    functions = "netlify/functions"
    publish = "dist"

[[redirects]]
  from = "/root/*"
  to = "https://firm-retina-435112-j9.uc.r.appspot.com"
  status = 200
  force = true

      [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200